import "@/styles/globals.css";
import { Toaster } from "sonner";
import type { Metadata } from "next";
import { LayoutProps } from "@/interface";
import PangaeAuthProvider from "@/lib/providers/pangae";
import DashboardNav from "@/components/global/dashboard-nav";
import NextTopLoader from "nextjs-toploader";
import RedirectWrapper from "@/components/global/redirect-wrapper";

export const metadata: Metadata = {
  title: "CloudCollab - Share file with teams.",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }: LayoutProps) => {
  return (
    <html lang="en">
      <body className="bg-slate-900">
        <PangaeAuthProvider>
          <RedirectWrapper>
            <NextTopLoader />
            <DashboardNav />
            <main>{children}</main>
          </RedirectWrapper>
        </PangaeAuthProvider>
        <Toaster position="top-center" richColors expand={false} />
      </body>
    </html>
  );
};

export default DashboardLayout;
