import "@/styles/globals.css";
import { Toaster } from "sonner";
import type { Metadata } from "next";
import { LayoutProps } from "@/interface";
import Sidebar from "@/components/global/sidebar";
import PangaeAuthProvider from "@/lib/providers/pangae";
import DashboardNav from "@/components/global/dashboard-nav";
import NextTopLoader from "nextjs-toploader";
import RedirectWrapper from "@/components/global/redirect-wrapper";

export const metadata: Metadata = {
  title: "CloudCollab - Share file with teams.",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children, params }: LayoutProps) => {
  return (
    <html lang="en">
      <body className="bg-slate-900">
        <PangaeAuthProvider>
          <RedirectWrapper>
            <NextTopLoader />
            <main className="flex-col w-screen h-screen overflow-hidden">
              <div className="flex h-full">
                <Sidebar orgId={params?.id} />
                <main className="grow h-full flex flex-col max-h-full overflow-x-hidden">
                  <DashboardNav />
                  <div className="grow flex flex-col overflow-hidden">
                    {children}
                  </div>
                </main>
              </div>
            </main>
          </RedirectWrapper>
        </PangaeAuthProvider>
        <Toaster position="top-center" richColors expand={false} />
      </body>
    </html>
  );
};

export default DashboardLayout;
