import type { Metadata } from "next";
import "@/styles/globals.css";
import { LayoutProps } from "@/interface";
import PangaeAuthProvider from "@/lib/providers/pangae";
import NextJsProgressbar from "@/lib/providers/nextjs-progressbar";
import ThemeProvider from "@/lib/providers/theme";
import { Toaster } from "sonner";
import Navbar from "@/components/global/navbar";
import Footer from "@/components/global/footer";

export const metadata: Metadata = {
  title: "MaaCloud - Share file with teams.",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: LayoutProps) => {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <NextJsProgressbar>
            <PangaeAuthProvider>
              <Navbar />
              {children}
              <Footer />
            </PangaeAuthProvider>
          </NextJsProgressbar>
          <Toaster position="top-center" richColors expand={false} />
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
