import type { Metadata } from "next";
import "@/styles/globals.css";
import { LayoutProps } from "@/interface";
import PangaeAuthProvider from "@/lib/providers/pangae";
import { Toaster } from "sonner";
import Sidebar from "@/components/global/sidebar";
import DashboardNav from "@/components/global/dashboard-nav";
import RedirectWrapper from "@/components/global/redirect-wrapper";

export const metadata: Metadata = {
  title: "MaaCloud - Share file with teams.",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }: LayoutProps) => {
  return (
    <html lang="en">
      <body className="bg-slate-900">
        <PangaeAuthProvider>
          <RedirectWrapper>
            <div className="flex-col">
              <div className="flex h-full">
                <Sidebar />
                <main className="grow h-full flex flex-col max-h-full overflow-x-hidden">
                  <DashboardNav />
                  <div className="grow flex flex-col">{children}</div>
                </main>
              </div>
            </div>
          </RedirectWrapper>
        </PangaeAuthProvider>
        <Toaster position="top-center" richColors expand={false} />
      </body>
    </html>
  );
};

export default DashboardLayout;
